[global]
title = "Tamiya-48-Bf-109E-3"
printName = "Tamiya-48-Bf-109E-3"
strokeColor = "red"
width = 120
height = 90

[points]
# the side of the main canopy, port
side1 = { x = 0, y = 0 }
side2 = { x = 156, y = 0 }
side3 = { x = 156, y = 68 }
side4 = { x = 0, y = 68 }

# the top of the canopy
top1 = { x = 0, y = 0 }
top2 = { x = 156, y = 0 }
top3 = { x = 156, y = 122 }
top4 = { x = 0, y = 122 }

# the triangle on the side of the windscreen, port
triangle1 = { x = 0, y = 0 }
triangle2 = { x = 0, y = 150 }
triangle3 = { x = 180, y = 150 }

# the trapezoid on the side of the windscreen, port
trap1 = { x = 30, y = 0 }
trap2 = { x = 70, y = 20 }
trap3 = { x = 70, y = 90 }
trap4 = { x = 0, y = 34 }

# top of windscreen
wtop1 = { x = 0, y = 24 }
wtop2 = { x = 42, y = 0 }
wtop3 = { x = 42, y = 122 }
wtop4 = { x = 0, y = 98 }

# windscreen itself
windscreen1 = { x =  0, y =  0 }
windscreen2 = { x = 42, y =  4 }
windscreen3 = { x = 42, y = 62 }
windscreen4 = { x =  0, y = 66 }

rear1 = { x = 112, y = 512 }
rear2 = { x = 496, y = 390 }
rear3 = { x = 488, y = 610 }

front1 = { x = 823, y = 415 }
front3 = { x = 1067, y = 422}
front4 = { x = 953, y = 549 }

[objects]
rear.curves = [
  "rear1 192,476 245,454 307,431 362,414 421,399 rear2",
  "rear3 454,610 390,604 327,593 272,579 204,555 154,536 rear1",
]
rear.lines = [
  "rear2 rear3"
]

side.lines = [
  "side1 side2 side3 side4 side1"
]

top.lines = [
  "top1 top2 top3 top4 top1"
]

triangle.lines = [
  "triangle1 triangle2 triangle3 triangle1"
]

trap.lines = [
  "trap1 trap2 trap3 trap4 trap1"
]

wtop.lines = [
  "wtop1 wtop2 wtop3 wtop4 wtop1"
]

windscreen.beziers = [
  "windscreen1 6,22 6,44 windscreen4"
]
windscreen.lines = [
  "windscreen1 windscreen2 windscreen3 windscreen4"
]

windscreenTop.lines = [
  "924,360 834,360 834,314 924,314 924,360"
]

front.curves = [
  "front1 895,384 981,396 front3",
  "front3 1035,470 992,517 front4",
  "front4 885,487 front1"
]

[[xrenders]]
object = "windscreen"
comment = "Windscreen"
translate = { x = 800, y = 400 }
flip = ""
hide = true

[[renders]]
object = "windscreen"
comment = "Windscreen"
translate = { x = 560, y = 460 }
flip = ""
scale = 2.25

[[xrenders]]
object = "windscreenTop"
comment = "Top of windscreen"
translate = { x = 400, y = 400 }
flip = ""
# scale = 1.5

[[xrenders]]
object = "front"
comment = "Windscreen side, flipped"
translate = { x = 1000, y = 250 }
flip = "vflip"

[[renders]]
object = "side"
comment = "Side of main canopy"
translate = { x = 950, y = 720 }
flip = ""
scale = 2.25

[[renders]]
object = "side"
comment = "Side of main canopy, flipped"
translate = { x = 950, y = 200 }
flip = "vflip"
scale = 2.25

[[renders]]
object = "top"
comment = "Top of main canopy"
translate = { x = 950, y = 430 }
flip = ""
scale = 2.25

[[renders]]
object = "wtop"
comment = "Top of windscreen"
translate = { x = 700, y = 440 }
flip = ""
scale = 2.25

[[renders]]
object = "trap"
comment = "Trapezoid on side of windscreen"
translate = { x = 660, y = 625 }
flip = ""
scale = 2.25

[[renders]]
object = "trap"
comment = "Trapezoid on side of windscreen, flipped"
translate = { x = 660, y = 280 }
flip = "vflip"
scale = 2.25

[[renders]]
object = "triangle"
comment = "Triangle on side of windscreen"
translate = { x = 625, y = 750 }
flip = ""
scale = 0.8

[[renders]]
object = "triangle"
comment = "Triangle on side of windscreen, flipped"
translate = { x = 625, y = 160 }
flip = "vflip"
scale = 0.8
