# Notes:
# The top of the main canopy is still a little wide.  I worked around it by
# cutting it in half lengthwise and applying each half separately, so there is
# a little overlap at the center.
# The triangle at the bottom of the side of the windscreen is still a bit too
# large.
# The windscreen could be a bit narrower, as could the top of the windscreen.

[global]
title = "Tamiya-48-Bf-109E-3"
printName = "Tamiya-48-Bf-109E-3"
strokeColor = "black"
physicalWidth = "180mm"
physicalHeight = "90mm"
width = 1800
height = 900
scale = 0.4
# scale = 1.4
strokeWidth = 1

[points]
# create a point representing the origin, as most objects use it
origin = { x = 0, y = 0 }

# the side of the main canopy, port
side1 = { x = 0, y = 0 }
side2 = { x = 150, y = 0 }
side3 = { x = 150, y = 68 }
side4 = { x = 0, y = 68 }

# the top of the canopy
top1 = { x =   0, y =   0 }
top2 = { x = 150, y =   0 }
top3 = { x = 150, y = 116 }
top4 = { x =   0, y = 116 }

# the triangle on the side of the windscreen, port
triangle1 = { x = 0, y = 0 }
triangle2 = { x = 0, y = 140 }
triangle3 = { x = 168, y = 140 }

# the trapezoid on the side of the windscreen, port
trap1 = { x = 30, y = 0 }
trap2 = { x = 70, y = 20 }
trap3 = { x = 70, y = 90 }
trap4 = { x = 0, y = 34 }

# top of windscreen
wtop1 = { x = 0, y = 24 }
wtop2 = { x = 46, y = 0 }
wtop3 = { x = 46, y = 122 }
wtop4 = { x = 0, y = 98 }

# windscreen itself
windscreen1 = { x =  0, y =  0 }
windscreen2 = { x = 42, y =  4 }
windscreen3 = { x = 42, y = 62 }
windscreen4 = { x =  0, y = 66 }

# rear side (triangle)
rside1 = { x =   0,  y =    0 }
rside2 = { x =   0,  y = 1260 }
rside3 = { x = 1000, y =    0 }

# rear top half
rtophalf1 = { x =   0, y = 300 }
rtophalf2 = { x =  50, y = 1400 }
rtophalf3 = { x = 1050, y = 1400 }
rtophalf4 = { x = 1450, y = 760 }
rtophalf5 = { x = 0, y = 0 }
rtophalf6 = { x = 0, y = 0 }
rtophalf7 = { x = 0, y = 0 }

# rear top
rtop1  = { x = 882, y = 57 }
rtop2  = { x = 876, y = 159 }
rtop3  = { x = 876, y = 204 }

rtop4a  = { x = 80, y = 110 }
rtop4b  = { x = 80, y = 170 }

rtop5  = { x = 72, y = 90 }
rtop6  = { x = 8, y = 0 }
rtop7  = { x = 0, y = 110 }
rtop8  = { x = 0, y = 170 }
rtop9  = { x = 8, y = 280 }
rtop10 = { x = 72, y = 190 }

[objects]
xrear.curves = [
"rear1 192,476 245,454 307,431 362,414 421,399 rear2",
"rear3 454,610 390,604 327,593 272,579 204,555 154,536 rear1",
]
rear.lines = [
"rtop10 rtop4b"
]

side.lines = [
"side1 side2 side3 side4 side1"
]
side.scale = 2.25

top.lines = [
"top1 top2 top3 top4 top1"
]
top.scale = 2.25

triangle.lines = [
"triangle1 triangle2 triangle3 triangle1"
]
triangle.scale = 0.8

trap.lines = [
"trap1 trap2 trap3 trap4 trap1"
]
trap.scale = 2.25

wtop.lines = [
"wtop1 wtop2 wtop3 wtop4 wtop1"
]
wtop.scale = 2.25

windscreen.beziers = [
"windscreen1 6,22 6,44 windscreen4"
]
windscreen.lines = [
"windscreen1 windscreen2 windscreen3 windscreen4"
]
windscreen.scale = 2.25

rside.lines = [
"rside1 rside2 rside3 rside1"
]
rside.scale = 0.16

rtop.lines = [
"rtop5 rtop6 rtop7 rtop8 rtop9 rtop10",
"rtop4a rtop4b"
]
rtop.scale = 2.25

rtophalf.lines = [
"rtophalf2 rtophalf3 rtophalf4"
]
rtophalf.curves = [
"origin rtophalf1 rtophalf2"
]
rtophalf.scale = 0.12

front.curves = [
"front1 895,384 981,396 front3",
"front3 1035,470 992,517 front4",
"front4 885,487 front1"
]

[[xrenders]]
object = "rear"
comment = "Rear"
translate = { x = 1600, y = 460 }
flip = ""
scale = 2.25

[[renders]]
object = "windscreen"
comment = "Windscreen"
translate = { x = 500, y = 450 }
flip = ""

[[xrenders]]
object = "rtop"
comment = "Rear top"
translate = { x = 1600, y = 460 }
flip = ""

[[xrenders]]
object = "rtophalf"
comment = "Rear top half"
translate = { x = 1260, y = 500 }
flip = ""

[[renders]]
object = "side"
comment = "Side of main canopy"
translate = { x = 950, y = 720 }
flip = ""

[[renders]]
object = "side"
comment = "Side of main canopy, flipped"
translate = { x = 950, y = 180 }
flip = "vflip"

[[renders]]
object = "top"
comment = "Top of main canopy"
translate = { x = 950, y = 450 }
flip = ""

[[renders]]
object = "triangle"
comment = "Triangle on side of windscreen"
translate = { x = 520, y = 720 }
flip = ""

[[renders]]
object = "triangle"
comment = "Triangle on side of windscreen, flipped"
translate = { x = 520, y = 180 }
flip = "vflip"

# These are OK.

[[renders]]
object = "trap"
comment = "Trapezoid on side of windscreen"
translate = { x = 620, y = 680 }
flip = ""

[[renders]]
object = "trap"
comment = "Trapezoid on side of windscreen, flipped"
translate = { x = 620, y = 220 }
flip = "vflip"

[[renders]]
object = "wtop"
comment = "Top of windscreen"
translate = { x = 660, y = 450 }
flip = ""

[[renders]]
object = "rside"
comment = "Rear side"
translate = { x = 1300, y = 720 }
flip = ""

[[renders]]
object = "rside"
comment = "Rear side, flipped"
translate = { x = 1300, y = 180 }
flip = "vflip"
