[global]
title = "Hasegawa J2M5/6"
# printName = "title"
physicalWidth = "180mm"
physicalHeight = "250mm"
width = 1800
height = 2500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }

[objects]
# objects can have curves, beziers, qbeziers, lines and segments
# obj.scale = 1.0

# w1, w2 => windscreen
# ws1, ws2 => windscreen side
# s1, s2, s3 => side
# t1, t2 => top
# armor => armor plate

w1.path = "M 85 130 L 849 249 Q 910 373, 853 511 L 85 656 Q 230 391, 85 130"
w1.scale = 0.5

w2.path = "M 74 262 L 272 96 Q 313 394, 272 692 L 74 526 Q 96 398, 74 262"
w2.scale = 0.5

ws1.path = "M 72 276 L 603 61 L 763 212 L 206 718 Z"
ws1.scale = 0.5

ws2.path = "M 90 631 L 679 82 L 697 90 L 571 739 Z"
ws2.scale = 0.5

s1.path = "M 98 95 L 425 108 L 439 714 L 106 686 Z"
s1.scale = 0.5

s2.path = "M 95 107 L 417 112 L 426 696 L 352 732 L 102 716 Z"
s2.scale = 0.5

s3.path = "M 88 67 L 681 138 L 708 166 L 693 689 L 672 711 L 108 684 Z"
s3.scale = 0.5

t1.path = "M 120 116 L 444 110 Q 420 396, 444 682 L 120 676 Q 100 396, 120 116"
t1.scale = 0.5

t2.path = "M 118 100 L 432 129 L 428 292   Q 362 284,  344 330   L 344 450   Q 362 480, 428 488 L 432 651 L 118 676 Q 104 388, 118 100"
t2.scale = 0.5

armor.path = "M 148 40 L 486 194 L 488 544 L 148 694 Z"
armor.scale = 0.5


[[renders]]
object = "w1"
translate = { x = 120, y = 100 }
scale = 0.23

[[xxxrenders]]
object = "w2"
translate = { x = 220, y = 100 }
scale = 0.35

[[need2fixrenders]]
object = "t1"
translate = { x = 300, y = 100 }
scale = 0.32

[[need2fixrenders]]
object = "t2"
translate = { x = 400, y = 100 }
scale = 0.32

[[renders]]
object = "ws1"
translate = { x = 120, y = 240 }
scale = 0.35
flip = "vflip"

[[renders]]
object = "ws2"
translate = { x = 200, y = 220 }
scale = 0.32
flip = "vflip"

[[need2vfliprenders]]
object = "s1"
translate = { x = 320, y = 250 }
scale = 0.38

[[need2vfliprenders]]
object = "s2"
translate = { x = 440, y = 250 }
scale = 0.38

[[renders]]
object = "s3"
# comment = ""
translate = { x = 580, y = 250 }
# flip = ""
scale = 0.38
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "armor"
translate = { x = 500, y = 100 }
scale = 0.26

