[global]
title = "Hasegawa J2M5/6"
# printName = "title"
physicalWidth = "180mm"
physicalHeight = "250mm"
width = 1800
height = 2500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }

[objects]
# objects can have curves, beziers, qbeziers, lines and segments
# obj.scale = 1.0

# w1, w2 => windscreen
# ws1, ws2 => windscreen side
# s1, s2, s3 => side
# t1, t2 => top
# armor => armor plate

ws1.path = "M 72 276 L 603 61 L 763 212 L 206 718 Z"
ws1.scale = 0.5

ws2.path = "M 90 631 L 679 82 L 697 90 L 571 739 Z"
ws2.scale = 0.5

s1.path = "M 98 95 L 425 108 L 439 714 L 106 686 Z"
s1.scale = 0.5

s2.path = "M 95 107 L 417 112 L 426 696 L 352 732 L 102 716 Z"
s2.scale = 0.5

s3.path = "M 93 67 L 681 138 L 708 166 L 693 689 L 672 711 L 108 684 Z"
s3.scale = 0.5

[[renders]]
object = "ws1"
translate = { x = 250, y = 500 }

[[renders]]
object = "ws2"
translate = { x = 420, y = 600 }

[[renders]]
object = "s3"
# comment = ""
translate = { x = 1300, y = 600 }
# flip = ""
# scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "s1"
translate = { x = 750, y = 600 }

[[renders]]
object = "s2"
translate = { x = 990, y = 600 }

