[global]
title = "Hasegawa 1/48 P-47D Bubbletop"
# printName = "title"
physicalWidth = "160mm"
physicalHeight = "50mm"
width = 1600
height = 500
scale = 1.0
strokeWidth = 1

[points]
ws1 = { x = 0, y = 350 }
ws2 = { x = 40, y = 110 }
ws2a = { x = 100, y = 70 }
ws3 = { x = 160, y = 110 }
ws4 = { x = 200, y = 350 }
ws4a = { x = 100, y = 310 }

s1 = { x = 0, y = 300 }
s2 = { x = 110, y = 100 }
s3 = { x = 160, y =  95 }
s4 = { x = 210, y = 260 }
# s5 = { x = 0, y = 300 }

c1 = { x = 0, y = 0 }
c1a = { x = 20, y = 100 }
c1b = { x = 20, y = 200 }
c2 = { x = 20, y = 300 }
c2a = { x = 200, y = 320 }
c2b = { x = 400, y = 320 }
c3 = { x = 600, y = 270 }
c4 = { x = 520, y = 200 }
c5 = { x = 120, y = 210 }
c6 = { x = 80, y = 10 }
c7 = { x = 0, y = 0 }
# p = { x = , y =  }
# p = { x = , y =  }
# p = { x = , y =  }
# p = { x = , y =  }

[objects]
ws.lines = [
"ws1 ws2",
"ws3 ws4"
]
ws.qbeziers = [
"ws2 ws2a ws3",
"ws4 ws4a ws1"
]
s.lines = [
"s1 s2 s3 s4 s1"
]
c.beziers = [
"c1 c1a c1b c2",
"c2 c2a c2b c3"
]
c.lines = [
"c3 c4 c5 c6 c1"
]

[[renders]]
object = "c"
comment = "Main canopy"
translate = { x = 800, y = 250 }
flip = ""
scale = 0.6
hide = true

[[renders]]
object = "ws"
comment = "Windscreen"
translate = { x = 200, y = 250 }
flip = ""
scale = 0.35
hide = false

[[renders]]
object = "s"
comment = "Side of windscreen"
translate = { x = 320, y = 300 }
flip = ""
scale = 0.4
hide = false
