[global]
title = "Hasegawa 1/48 P-47D Bubbletop"
# printName = "title"
physicalWidth = "120mm"
physicalHeight = "80mm"
width = 1200
height = 800
scale = 1.0
strokeWidth = 1

[points]
ws1 = { x = 0, y = 300 }
ws2 = { x = 40, y = 100 }
ws2a = { x = 80, y = 70 }
ws3 = { x = 120, y = 100 }
ws4 = { x = 160, y = 300 }
ws4a = { x = 80, y = 270 }
# p = { x = , y =  }
# p = { x = , y =  }
# p = { x = , y =  }
# p = { x = , y =  }
# p = { x = , y =  }
# p = { x = , y =  }

[objects]
ws.lines = [
"ws1 ws2",
"ws3 ws4"
]
ws.qbeziers = [
"ws2 ws2a ws3",
"ws4 ws4a ws1"
]

[[renders]]
object = "ws"
comment = "Windscreen"
translate = { x = 600, y = 400 }
flip = ""
hide = false
