[global]
title = "Hasegawa-48-Ki-44"
image = "Hasegawa-48-Ki-44-1.jpg"
strokeColor = "black"
strokeWidth = 2
printName = "Hasegawa-48-Ki-44"

[points]

[objects]
part1.curves = [
  "string1",
  "string2"
]
part1.lines = [
  "line1",
  "line2",
  "line3"
]
