[global]
title = "Revell P-47D Razorback"
# printName = "title"
physicalWidth = "150mm"
physicalHeight = "150mm"
width = 1500
height = 1500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }
wside1 = { x = 150, y = 130 }
wside2 = { x = -75, y = 62 }

[objects]

# sideFront is OK
sideFront.lines = [
"0,0 105,0 105,120 0,120 0,0"
]

# sideRear is OK
sideRear.lines = [
"0,0 100,0 100,120 0,120 0,0"
]

# topFront is OK
topFront.lines = [
"0,0 135,0 135,105 -5,105 0,0"
]

# topRear is OK
topRear.lines = [
"0,0 140,0 135,100 5,100 0,0"
]

# razor is OK
razor.lines = [
"-10,0 70,0 190,130 -10,130 -10,0"
]

# wside is OK
wside.lines = [
"-1,0 136,0 wside1",
"wside2 -1,0"
]
wside.beziers = [
"wside1 70,110 60,95 wside2"
]

wtopcenter.qbeziers = [
"0,-25 35,0 0,25"
]
wtopcenter.lines = [
"0,25 0,40 50,40 50,-40 0,-40 0,-25"
]

wtop.beziers = [
"0,80 100,75 120,55 200,0"
]
wtop.lines = [
"200,0 160,0 100,35 0,35 0,80"
]

# commented out by renaming object
xwtop.qbeziers = [
"0,-25 40,0 0,25"
]
xwtop.lines = [
"0,25 0,60",
"0,-60 0,-25"
]
xwtop.beziers = [
"0,60 50,55 80,50 130,0",
"130,0 80,-50 50,-55 0,-60"
]

[[renders]]
object = "sideFront"
translate = { x = 100, y = 100 }
scale = 1.0
hide = true

[[renders]]
object = "sideRear"
translate = { x = 100, y = 100 }
scale = 1.0
hide = true

[[renders]]
object = "topFront"
translate = { x = 300, y = 100 }
scale = 1.0
hide = true

[[renders]]
object = "topRear"
translate = { x = 400, y = 240 }
scale = 1.0
hide = true

[[renders]]
object = "razor"
translate = { x = 330, y = 100 }
scale = 1.0
hide = true

[[renders]]
object = "wside"
translate = { x = 140, y = 140 }
scale = 1.0
hide = true

[[renders]]
object = "wtop"
translate = { x = 340, y = 100 }
scale = 1.0

[[renders]]
object = "wtopcenter"
translate = { x = 140, y = 100 }
scale = 1.0
# hide = true
