[global]
title = "Revell P-47D Razorback"
# printName = "title"
physicalWidth = "150mm"
physicalHeight = "150mm"
width = 1500
height = 1500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }
wside1 = { x = 142, y = 130 }
wside2 = { x = -70, y = 72 }

[objects]

# side seems OK
sideFront.lines = [
"0,0 100,0 100,120 0,120 0,0"
]

# dimensionally OK, but needs to curve a bit
topFront.lines = [
"130,0 130,100",
"0,100 0,0"
]
topFront.qbeziers = [
"0,0 65,-5 130,0",
"130,100 65,95 0,100"
]

# dimensionally OK, but needs to curve a bit
topRear.lines = [
"120,0 120,90",
"0,90 0,0"
]
topRear.qbeziers = [
"0,0 60,-5 120,0",
"120,90 60,85 0,90"
]

# razor seems OK
razor.lines = [
"0,0 70,0 186,120 0,120 0,0"
]

wside.lines = [
"4,0 136,0 wside1",
"wside2 4,0"
]
wside.beziers = [
"wside1 70,110 60,95 wside2"
]

wtop.qbeziers = [
"0,-25 25,0 0,25"
]
wtop.lines = [
"0,25 0,70",
"0,-70 0,-25"
]
wtop.beziers = [
"0,70 50,55 70,50 120,0",
"120,0 70,-50 50,-55 0,-70"
]

[[renders]]
object = "sideFront"
# comment = ""
translate = { x = 100, y = 100 }
# flip = ""
scale = 1.0
hide = true
# aspect = 1.0 # width to height ratio

[[renders]]
object = "sideFront"
# comment = ""
translate = { x = 100, y = 300 }
# flip = ""
scale = 1.0
hide = true
# aspect = 1.0 # width to height ratio

[[renders]]
object = "topFront"
translate = { x = 400, y = 100 }
scale = 1.0

[[renders]]
object = "topRear"
translate = { x = 400, y = 240 }
scale = 1.0

[[renders]]
object = "razor"
# comment = ""
translate = { x = 660, y = 100 }
# flip = ""
scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "wside"
# comment = ""
translate = { x = 140, y = 140 }
# flip = ""
scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "wtop"
# comment = ""
translate = { x = 140, y = 300 }
# flip = ""
scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio
