[global]
title = "Revell P-47D Razorback"
# printName = "title"
physicalWidth = "150mm"
physicalHeight = "150mm"
width = 1500
height = 1500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }
wside1 = { x = 147, y = 130 }
wside2 = { x = -80, y = 62 }

[objects]

# side seems OK - need to verify with actual mask
sideFront.lines = [
"0,0 100,0 100,120 0,120 0,0"
]

topFront.lines = [
"0,0 135,0 135,105 0,105 0,0"
]

topRear.lines = [
"0,0 140,0 140,100 0,100 0,0"
]

razor.lines = [
"-20,0 70,0 186,125 -20,125 -20,0"
]

wside.lines = [
"-1,0 136,0 wside1",
"wside2 -1,0"
]
wside.beziers = [
"wside1 70,110 60,95 wside2"
]

wtop.qbeziers = [
"0,-25 40,0 0,25"
]
wtop.lines = [
"0,25 0,60",
"0,-60 0,-25"
]
wtop.beziers = [
"0,60 50,55 70,50 130,0",
"130,0 70,-50 50,-55 0,-60"
]

[[renders]]
object = "sideFront"
# comment = ""
translate = { x = 100, y = 100 }
# flip = ""
scale = 1.0
hide = true
# aspect = 1.0 # width to height ratio

[[renders]]
object = "sideFront"
# comment = ""
translate = { x = 100, y = 300 }
# flip = ""
scale = 1.0
hide = true
# aspect = 1.0 # width to height ratio

[[renders]]
object = "topFront"
translate = { x = 400, y = 100 }
scale = 1.0

[[renders]]
object = "topRear"
translate = { x = 400, y = 240 }
scale = 1.0

[[renders]]
object = "razor"
# comment = ""
translate = { x = 660, y = 100 }
# flip = ""
scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "wside"
# comment = ""
translate = { x = 140, y = 140 }
# flip = ""
scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "wtop"
# comment = ""
translate = { x = 140, y = 300 }
# flip = ""
scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio
