[global]
title = "Revell P-47D Razorback"
# printName = "title"
physicalWidth = "150mm"
physicalHeight = "50mm"
width = 1500
height = 500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }
wside1 = { x = 150, y = 130 }
wside2 = { x = -75, y = 62 }

[objects]

# sideFront is OK
sideFront.lines = [
"0,0 105,0 105,120 0,120 0,0"
]

# sideRear is OK
sideRear.lines = [
"0,0 100,0 100,120 0,120 0,0"
]

# topFront is OK
topFront.lines = [
"0,0 135,0 135,105 -5,105 0,0"
]

# topRear is OK
topRear.lines = [
"0,0 140,0 135,100 5,100 0,0"
]

# razor is OK
razor.lines = [
"-10,0 70,0 190,130 -10,130 -10,0"
]

# wside is OK
wside.lines = [
"-1,0 136,0 wside1",
"wside2 -1,0"
]
wside.beziers = [
"wside1 70,110 60,95 wside2"
]

# wtopcenter is OK
wtopcenter.qbeziers = [
"0,-25 35,0 0,25"
]
wtopcenter.lines = [
"0,25 0,40 50,30 50,-30 0,-40 0,-25"
]

# wtop is OK
wtop.beziers = [
"0,80 60,75 60,75 135,50"
]
wtop.lines = [
"135,50 100,30 55,40 5,45 0,80"
]


[[renders]]
object = "sideFront"
translate = { x = 560, y = 100 }
scale = 1.0

[[renders]]
object = "sideRear"
translate = { x = 700, y = 100 }
scale = 1.0

[[renders]]
object = "razor"
translate = { x = 880, y = 100 }
scale = 1.0

[[renders]]
object = "sideFront"
translate = { x = 560, y = 300 }
scale = 1.0
flip="vflip"

[[renders]]
object = "sideRear"
translate = { x = 700, y = 300 }
scale = 1.0
flip="vflip"

[[renders]]
object = "razor"
translate = { x = 880, y = 300 }
scale = 1.0
flip="vflip"

[[renders]]
object = "topFront"
translate = { x = 1100, y = 120 }
scale = 1.0

[[renders]]
object = "topRear"
translate = { x = 1100, y = 280 }
scale = 1.0

[[renders]]
object = "razor"
translate = { x = 330, y = 100 }
scale = 1.0
hide = true

[[renders]]
object = "wside"
translate = { x = 360, y = 280 }
scale = 1.0

[[renders]]
object = "wside"
translate = { x = 360, y = 100 }
scale = 1.0
flip="vflip"

[[renders]]
object = "wtop"
translate = { x = 120, y = 300 }
scale = 1.0

[[renders]]
object = "wtop"
translate = { x = 120, y = 220 }
scale = 1.0
flip="vflip"

[[renders]]
object = "wtopcenter"
translate = { x = 100, y = 100 }
scale = 1.0
