[global]
title = "48-Hasegawa-Ki-44-wings"
printName = "48-Hasegawa-Ki-44-wings"
physicalWidth = "180mm"
physicalHeight = "90mm"
width = 1800
height = 660
# scale = 0.4
scale = 1.4
strokeWidth = 1

[points]

innertop1 = { x = 576, y = 297}
innertop2 = { x = 603, y = 251}
innertop3 = { x = 855, y = 259}
innertop4 = { x = 852, y = 317}

innerbottom1 = { x = 149, y = 26 }
innerbottom2 = { x = 134, y = 102 }
innerbottom3 = { x = 296, y = 102 }
innerbottom4 = { x = 388, y = 63 }

[objects]

innertop.lines = [
"innertop1 innertop2"
]
innertop.curves = [
"innertop2 664,264 755,272 innertop3",
"innertop3 861,288 innertop4",
"innertop4 748,328 632,318 innertop1"
]

innerbottom.lines = [
"innerbottom1 innerbottom4 innerbottom3"
]
innerbottom.beziers = [
"innerbottom1 130,48 122,68 innerbottom2",
"innerbottom2 166,82 228,84 innerbottom3"
]

[[renders]]
object = "innertop"
comment = "Inner section, top of wing"
translate = { x = 1200, y = 180 }
flip = ""
scale = 2.2

[[renders]]
object = "innertop"
comment = "Inner section, top of wing, flipped"
translate = { x = 1200, y = 420 }
flip = "vflip"
scale = 2.2

[[renders]]
object = "innerbottom"
comment = "Inner section, bottom of wing"
translate = { x = 400, y = 160 }
flip = ""
scale = 2.2

[[renders]]
object = "innerbottom"
comment = "Inner section, bottom of wing, flipped"
translate = { x = 400, y = 400 }
flip = "vflip"
scale = 2.2
