[global]
title = "Hasegawa Macchi"
# printName = "title"
physicalWidth = "150mm"
physicalHeight = "60mm"
width = 1500
height = 600
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }

[objects]
side.lines = [
"0,0 220,0 220,250 0,250 0,0"
]
side.scale = 0.24

top.lines = [
"0,0 130,0 130,240 0,240 0,0"
]
top.scale = 0.25

windscreen.lines = [
"0,250 0,0 140,0 140,250"
]
windscreen.beziers = [
"140,250 130,290 10,290 0,250"
]
windscreen.scale = 0.18

triangle.lines = [
"260,0 130,225 0,0"
]
triangle.qbeziers = [
"0,0 130,30 260,0"
]
triangle.segments = [
"80,205 180,205"
]
triangle.scale = 0.27

[[renders]]
object = "side"
translate = { x = 100, y = 100 }

[[renders]]
object = "side"
translate = { x = 200, y = 100 }

[[renders]]
object = "side"
translate = { x = 100, y = 230 }

[[renders]]
object = "side"
translate = { x = 200, y = 230 }

[[renders]]
object = "top"
translate = { x = 300, y = 100 }

[[renders]]
object = "top"
translate = { x = 360, y = 100 }

[[renders]]
object = "top"
translate = { x = 420, y = 100 }

[[renders]]
object = "windscreen"
translate = { x = 500, y = 100 }

[[renders]]
object = "triangle"
translate = { x = 320, y = 230 }

[[renders]]
object = "triangle"
translate = { x = 420, y = 230 }
