[global]
title = "Tamiya Me262"
# printName = "title"
physicalWidth = "180mm"
physicalHeight = "250mm"
width = 1800
height = 2500
scale = 1.0
strokeWidth = 1
# strokeColor = "black"

[points]
# p = { x = , y =  }

[objects]
# objects can have curves, beziers, qbeziers, lines and segments
# obj.scale = 1.0

# w is windscreen
wside.lines = [
"0,0 70,0 55,60"
]
wside.qbeziers = [
"55,60 33,27 0,0"
]
wfront.lines = [
"0,0 80,12 80,50 0,62"
]
wfront.qbeziers = [
"0,62 15,31 0,0"
]

# c is main canopy
cbottom.lines = [
"0,0 140,0 150,50 -10,50 0,0"
]
ctop.lines = [
"190,0 180,50 10,50 0,0"
]
ctop.qbeziers = [
"0,0 90,-10 190,0"
]

# r is rear canopy
rbottom.lines = [
"110,20 110,0 0,0",
"-10,110 20,110"
]
rbottom.qbeziers = [
"0,0 0,70 -10,110",
"20,110 65,65 110,20"
]

[[renders]]
object = "wside"
# comment = ""
translate = { x = 100, y = 300 }
# flip = ""
# scale = 1.0
# hide = false
# aspect = 1.0 # width to height ratio

[[renders]]
object = "wfront"
# comment = ""
translate = { x = 120, y = 200 }

[[renders]]
object = "cbottom"
# comment = ""
translate = { x = 300, y = 300 }
flip = "vflip"

[[renders]]
object = "ctop"
# comment = ""
translate = { x = 300, y = 200 }

[[renders]]
object = "rbottom"
# comment = ""
translate = { x = 500, y = 300 }
