[global]
title = "Tamiya 1/48 Fw 190"
printName = "Tamiya-48-Fw-190"
physicalWidth = "180mm"
physicalHeight = "250mm"
width = 1800
height = 2500
scale = 1.0
strokeWidth = 1

[points]
rear1 = { x = 112, y = 512 }
rear2 = { x = 496, y = 390 }
rear3 = { x = 488, y = 610 }
side1 = { x = 519, y = 389 }
side2 = { x = 772, y = 373 }
side3 = { x = 819, y = 598 }
side4 = { x = 515, y = 608 }
front1 = { x = 823, y = 415 }
front3 = { x = 1067, y = 422}
front4 = { x = 953, y = 549 }

[objects]
windscreen.lines = [
"0,0 90,0 90,48 0,48 0,0"
]

side.lines = [
"0,0 80,0 62,78 0,0"
]

rside.lines = [
"0,0 190,0 220,50 -10,90 0,0"
]
rside.segments = [
"-10,15 10,-5",
"80,-10 80,90"
]


[[renders]]
object = "windscreen"
comment = "Windscreen"
translate = { x = 100, y = 200 }
flip = ""
scale = 0.96
hide = true

[[renders]]
object = "side"
comment = "Side"
translate = { x = 100, y = 300 }
flip = ""
hide = true

[[renders]]
object = "side"
comment = "Side"
translate = { x = 100, y = 100 }
flip = "vflip"
hide = true

[[renders]]
object = "rside"
comment = "Side of blown canopy"
translate = { x = 300, y = 300 }
flip = "vflip"
