[global]
title = "Tamiya 1/48 Fw 190"
printName = "Tamiya-48-Fw-190"
physicalWidth = "180mm"
physicalHeight = "250mm"
width = 1800
height = 2500
scale = 1.0
strokeWidth = 1

[points]
rear1 = { x = 112, y = 512 }
rear2 = { x = 496, y = 390 }
rear3 = { x = 488, y = 610 }
side1 = { x = 519, y = 389 }
side2 = { x = 772, y = 373 }
side3 = { x = 819, y = 598 }
side4 = { x = 515, y = 608 }
front1 = { x = 823, y = 415 }
front3 = { x = 1067, y = 422}
front4 = { x = 953, y = 549 }

[objects]
windscreen.lines = [
"0,0 90,0 90,48 0,48 0,0"
]

side.lines = [
"0,0 80,0 62,78 0,0"
]

rside.lines = [
"0,0 190,0 230,66 120,90 -10,90 0,0"
]
rside.segments = [
"-10,15 10,-5",
"80,-10 80,100"
]

# rside1 is lower left
rside1.lines = [
"0,0 80,0 70,80 -10,90 0,0"
]

# rside2 is lower right
rside2.lines = [
"130,0 190,0 220,50 130,50 130,0"
]

# rside3 is upper right
rside3.lines = [
"100,0 120,50 50,60 50,0 100,0"
]

# rside4 is upper left
rside4.lines = [
"60,0 0,0 -10,20 -10,60 60,60 60,0"
]


[[renders]]
object = "windscreen"
comment = "Windscreen"
translate = { x = 100, y = 180 }
flip = ""
scale = 0.96
# hide = true

[[renders]]
object = "side"
comment = "Side"
translate = { x = 100, y = 280 }
flip = ""
# hide = true

[[renders]]
object = "side"
comment = "Side"
translate = { x = 100, y = 80 }
flip = "vflip"
# hide = true

[[renders]]
object = "rside1"
comment = "Side of blown canopy"
translate = { x = 240, y = 260 }
flip = "vflip"

[[renders]]
object = "rside1"
comment = "Side of blown canopy"
translate = { x = 240, y = 120 }
flip = ""

[[renders]]
object = "rside2"
comment = "Side of blown canopy"
translate = { x = 380, y = 260 }
flip = "vflip"

[[renders]]
object = "rside2"
comment = "Side of blown canopy"
translate = { x = 380, y = 120 }

[[renders]]
object = "rside3"
comment = "Side of blown canopy"
translate = { x = 400, y = 200 }
flip = "vflip"
hide = true

[[renders]]
object = "rside4"
comment = "Side of blown canopy"
translate = { x = 300, y = 200 }
flip = "vflip"
hide = true
